# Exercise 5.A NumPy Fundamentals

This notebook practices creating and working with NumPy arrays.

In [8]:
import numpy as np

## Array Basics

In [5]:
fruits = ["apple", "banana", "cherry", "date"]

In [9]:
arr_1 = np.array(fruits)
print(arr_1)

['apple' 'banana' 'cherry' 'date']


In [11]:
# The dtype shows the type of data stored in the array.
# The letter U means Unicode string.
# The number means the maximum number of characters in the string values.

In [13]:
arr_2 = np.array([
    [10, 11, 12],
    [13, 14, 15]])

print(arr_2)

[[10 11 12]
 [13 14 15]]


In [14]:
print(arr_2.T)

# No, this does not permanently change arr_2.
# It only displays a transposed version.

[[10 13]
 [11 14]
 [12 15]]


In [16]:
arr_3 = np.array([
    [1, 3, 5],
    [2, 4, 6]])

print(arr_3)

[[1 3 5]
 [2 4 6]]


In [17]:
arr_4 = np.array([arr_3[0, 2], arr_3[1, 1]])

print(arr_4)

[5 4]


In [18]:
arr_5 = np.ones((2, 2, 2))

print(arr_5)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
